// A faithful port of the research reference implementation
// (research/thetashield/model.py) — the same code the evidence bundle was
// generated by, and which test/integration/GoldenVectors.t.sol and
// research/tests/test_golden_vectors.py check the Solidity and Python against.
//
// It exists so the page can show what the DEPLOYED curve would return for inputs
// a visitor chooses, without inventing a second source of truth.
// tests/fee-model.test.mjs runs every function below against
// research/datasets/golden_vectors.json — the same file that gates the contract.
// If this port drifts from the contract, that suite fails.
//
// All arithmetic is bigint in WAD. Python's `//` floors; JS bigint `/` truncates
// toward zero. Every division below has a NON-NEGATIVE numerator (the reference
// takes abs() or guards on > 0 first), so the two agree — except
// directionalMarkout, which the reference deliberately routes through a
// truncating divide, ported here as truncDiv.

export const WAD = 1_000_000_000_000_000_000n;
export const FEE_PIPS = 1_000_000n;

/** Round-toward-zero division, matching Solidity signed division. */
export function truncDiv(numerator: bigint, denominator: bigint): bigint {
  if (denominator === 0n) throw new Error("division by zero");
  const magnitude =
    (numerator < 0n ? -numerator : numerator) / (denominator < 0n ? -denominator : denominator);
  return numerator < 0n !== denominator < 0n ? -magnitude : magnitude;
}

function abs(value: bigint): bigint {
  return value < 0n ? -value : value;
}

/** Integer square root, matching Python's math.isqrt. */
function isqrt(value: bigint): bigint {
  if (value < 0n) throw new Error("isqrt of a negative");
  if (value < 2n) return value;
  let low = 0n;
  let high = value;
  while (low < high) {
    const mid = (low + high + 1n) / 2n;
    if (mid * mid <= value) low = mid;
    else high = mid - 1n;
  }
  return low;
}

/** d × (reference − execution) / execution, in WAD. */
export function directionalMarkout(
  executionPriceWad: bigint,
  referencePriceWad: bigint,
  direction: 1 | -1,
): bigint {
  if (executionPriceWad <= 0n) throw new Error("execution price must be positive");
  if (referencePriceWad < 0n) throw new Error("reference price cannot be negative");
  const move = truncDiv((referencePriceWad - executionPriceWad) * WAD, executionPriceWad);
  return BigInt(direction) * move;
}

/** Integer population standard deviation in WAD. */
export function populationSigma(valuesWad: bigint[]): bigint {
  if (valuesWad.length < 2) return 0n;
  const count = BigInt(valuesWad.length);
  const meanWad = truncDiv(valuesWad.reduce((total, value) => total + value, 0n), count);
  const varianceWadSquared =
    valuesWad.reduce((total, value) => total + (value - meanWad) ** 2n, 0n) / count;
  return isqrt(varianceWadSquared);
}

/** Scores index i using [max(0, i−W), i) — never including i itself. */
export function trailingSigma(
  markoutsWad: bigint[],
  currentIndex: number,
  window: number,
): { sigmaWad: bigint; sampleCount: number } {
  if (window <= 0) throw new Error("window must be positive");
  if (currentIndex < 0 || currentIndex > markoutsWad.length) throw new Error("index outside series");
  const trailing = markoutsWad.slice(Math.max(0, currentIndex - window), currentIndex);
  return { sigmaWad: populationSigma(trailing), sampleCount: trailing.length };
}

/** sign(m) × max(|m| − k·sigma, 0). */
export function deadBandFilter(markoutWad: bigint, sigmaWad: bigint, kWad: bigint): bigint {
  if (sigmaWad < 0n || kWad < 0n) throw new Error("sigma and k must be non-negative");
  const bandWad = (sigmaWad * kWad) / WAD;
  const excessWad = abs(markoutWad) - bandWad;
  const clamped = excessWad > 0n ? excessWad : 0n;
  return markoutWad < 0n ? -clamped : clamped;
}

/** The band alone, for display beside the filtered value. */
export function deadBand(sigmaWad: bigint, kWad: bigint): bigint {
  return (sigmaWad * kWad) / WAD;
}

export type ConfidenceComponents = {
  countScoreWad: bigint;
  agreementScoreWad: bigint;
  dispersionScoreWad: bigint;
  uncappedConfidenceWad: bigint;
  confidenceWad: bigint;
};

export function calculateConfidence(input: {
  observationCount: bigint;
  targetObservationCount: bigint;
  agreeingNotionalWad: bigint;
  totalNotionalWad: bigint;
  referenceDispersionWad: bigint;
  maximumDispersionWad: bigint;
  confidenceCapWad: bigint;
}): ConfidenceComponents {
  const {
    observationCount, targetObservationCount, agreeingNotionalWad,
    totalNotionalWad, referenceDispersionWad, maximumDispersionWad, confidenceCapWad,
  } = input;
  if (targetObservationCount <= 0n || totalNotionalWad <= 0n || maximumDispersionWad <= 0n) {
    throw new Error("confidence denominators must be positive");
  }
  if (observationCount < 0n || referenceDispersionWad < 0n) {
    throw new Error("confidence inputs cannot be negative");
  }
  if (agreeingNotionalWad < 0n || agreeingNotionalWad > totalNotionalWad) {
    throw new Error("agreeing notional is outside total notional");
  }

  const counted = observationCount < targetObservationCount ? observationCount : targetObservationCount;
  const countScoreWad = (counted * WAD) / targetObservationCount;
  const agreementWad = (agreeingNotionalWad * WAD) / totalNotionalWad;
  const agreementRaw = (agreementWad - WAD / 2n) * 2n;
  const agreementScoreWad = agreementRaw > 0n ? agreementRaw : 0n;
  const dispersionSlack = maximumDispersionWad - referenceDispersionWad;
  const dispersionScoreWad = ((dispersionSlack > 0n ? dispersionSlack : 0n) * WAD) / maximumDispersionWad;
  const countAgreementWad = (countScoreWad * agreementScoreWad) / WAD;
  const uncappedConfidenceWad = (countAgreementWad * dispersionScoreWad) / WAD;
  return {
    countScoreWad,
    agreementScoreWad,
    dispersionScoreWad,
    uncappedConfidenceWad,
    confidenceWad:
      uncappedConfidenceWad < confidenceCapWad ? uncappedConfidenceWad : confidenceCapWad,
  };
}

/** Shifts one epoch into the bitmap and reports the n-of-k verdict. */
export function pushPersistence(
  bitmap: bigint,
  toxic: boolean,
  requiredToxicEpochs: number,
  windowLength: number,
): { bitmap: bigint; active: boolean } {
  if (!(requiredToxicEpochs >= 1 && requiredToxicEpochs <= windowLength && windowLength <= 256)) {
    throw new Error("invalid n-of-k persistence configuration");
  }
  const mask = (1n << BigInt(windowLength)) - 1n;
  const updated = ((bitmap << 1n) | (toxic ? 1n : 0n)) & mask;
  let lit = 0;
  for (let bit = 0n; bit < BigInt(windowLength); bit += 1n) {
    if ((updated >> bit) & 1n) lit += 1;
  }
  return { bitmap: updated, active: lit >= requiredToxicEpochs };
}

/** EWMA magnitude, then the current aggregate's sign and confidence. */
export function smoothDirectionalRisk(input: {
  aggregateMarkoutWad: bigint;
  previousMagnitudeWad: bigint;
  alphaWad: bigint;
  confidenceWad: bigint;
}): { magnitudeWad: bigint; signedRiskWad: bigint } {
  const { aggregateMarkoutWad, previousMagnitudeWad, alphaWad, confidenceWad } = input;
  if (previousMagnitudeWad < 0n) throw new Error("previous magnitude cannot be negative");
  const magnitudeWad =
    (abs(aggregateMarkoutWad) * alphaWad) / WAD + (previousMagnitudeWad * (WAD - alphaWad)) / WAD;
  const riskMagnitudeWad = (magnitudeWad * confidenceWad) / WAD;
  const direction = aggregateMarkoutWad > 0n ? 1n : aggregateMarkoutWad < 0n ? -1n : 0n;
  return { magnitudeWad, signedRiskWad: direction * riskMagnitudeWad };
}

export type FeeConfig = {
  baseFeePips: bigint;
  minimumFeePips: bigint;
  maximumFeePips: bigint;
  gainFeePips: bigint;
  maximumIncreasePips: bigint;
  maximumDecreasePips: bigint;
  confidenceFloorWad: bigint;
};

/** Maps positive active risk to a bounded, rate-limited directional fee. */
export function calculateFee(input: {
  signedRiskWad: bigint;
  confidenceWad: bigint;
  persistenceActive: boolean;
  previousFeePips: bigint;
  config: FeeConfig;
}): { premiumPips: bigint; targetFeePips: bigint; nextFeePips: bigint } {
  const { signedRiskWad, confidenceWad, persistenceActive, previousFeePips, config } = input;
  if (
    !(config.minimumFeePips <= config.baseFeePips &&
      config.baseFeePips <= config.maximumFeePips &&
      config.maximumFeePips <= FEE_PIPS)
  ) {
    throw new Error("invalid fee bounds");
  }
  if (previousFeePips < config.minimumFeePips || previousFeePips > config.maximumFeePips) {
    throw new Error("previous fee is outside configured bounds");
  }

  let premiumPips = 0n;
  if (persistenceActive && confidenceWad >= config.confidenceFloorWad && signedRiskWad > 0n) {
    premiumPips = (signedRiskWad * config.gainFeePips) / WAD;
    const maximumPremium = config.maximumFeePips - config.baseFeePips;
    if (premiumPips > maximumPremium) premiumPips = maximumPremium;
  }

  const raised = config.baseFeePips + premiumPips;
  const floored = raised > config.minimumFeePips ? raised : config.minimumFeePips;
  const targetFeePips = floored < config.maximumFeePips ? floored : config.maximumFeePips;

  let nextFeePips: bigint;
  if (targetFeePips > previousFeePips) {
    const ceiling = previousFeePips + config.maximumIncreasePips;
    nextFeePips = targetFeePips < ceiling ? targetFeePips : ceiling;
  } else {
    const floor = previousFeePips - config.maximumDecreasePips;
    nextFeePips = targetFeePips > floor ? targetFeePips : floor;
    const lifted = nextFeePips > config.minimumFeePips ? nextFeePips : config.minimumFeePips;
    nextFeePips = lifted < config.maximumFeePips ? lifted : config.maximumFeePips;
  }
  return { premiumPips, targetFeePips, nextFeePips };
}
