// Renders docs/THETASHIELD_FLOW.excalidraw to docs/THETASHIELD_FLOW.png.
//
// The canvas itself is generated by script/gen_flow_diagram.py from the
// deployment manifest, for the reason that script gives: a drawing is a claim
// about the deployment made once, and this deployment moves. A hand-exported
// PNG would reintroduce exactly the drift the generator exists to prevent, so
// the picture is rendered from the same source rather than saved out of an app.
//
// Excalidraw draws with rough.js, so a plain SVG rasteriser produces clean
// geometry that does not match what the .excalidraw file looks like when
// opened. This drives Excalidraw's own exporter in headless Chrome instead, at
// scale 1 — the canvas is authored at its final pixel size, so 1:1 is both the
// intended reading size and the smallest faithful one.
//
// Deliberately NOT part of `make verify`: it needs Chrome and the npm CDN, and
// a release gate should not depend on either. Run `make diagram-png` after
// `make diagram` when the canvas changes.
import { spawn } from "node:child_process";
import { readFileSync, writeFileSync, rmSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SCENE = join(REPO, "docs", "THETASHIELD_FLOW.excalidraw");
const OUT = join(REPO, "docs", "THETASHIELD_FLOW.png");
const CHROME = process.env.CHROME_BINARY
  ?? "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const PORT = Number(process.env.CDP_PORT ?? 9350);
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const scene = readFileSync(SCENE, "utf8");
// A literal </script> inside the JSON would close the tag early.
const sceneForHtml = scene.split("</").join("<\\/");
const work = mkdtempSync(join(tmpdir(), "thetashield-flow-"));
const page = join(work, "render.html");
writeFileSync(page, `<!doctype html><meta charset="utf-8"><body style="margin:0;background:#fff">
<script src="https://unpkg.com/react@18.2.0/umd/react.production.min.js"></script>
<script src="https://unpkg.com/react-dom@18.2.0/umd/react-dom.production.min.js"></script>
<script src="https://unpkg.com/@excalidraw/excalidraw@0.17.6/dist/excalidraw.production.min.js"></script>
<script id="scene" type="application/json">${sceneForHtml}</script>
<script>
window.__done = false; window.__err = null; window.__png = null;
(async () => {
  try {
    const lib = window.ExcalidrawLib;
    if (!lib) throw new Error("ExcalidrawLib did not load — check network access to unpkg");
    const s = JSON.parse(document.getElementById("scene").textContent);
    const blob = await lib.exportToBlob({
      elements: s.elements,
      appState: { ...(s.appState || {}), exportBackground: true,
                  viewBackgroundColor: "#ffffff", exportWithDarkMode: false },
      files: s.files || {}, mimeType: "image/png", quality: 1, exportPadding: 32,
      getDimensions: (w, h) => ({ width: w, height: h, scale: 1 }),
    });
    const bytes = new Uint8Array(await blob.arrayBuffer());
    let out = ""; for (let i = 0; i < bytes.length; i += 1) out += String.fromCharCode(bytes[i]);
    window.__png = btoa(out);
  } catch (e) { window.__err = String((e && e.stack) || e); }
  window.__done = true;
})();
</script></body>`);

const profile = join(work, "profile");
const chrome = spawn(CHROME, ["--headless=new", "--disable-gpu", "--hide-scrollbars",
  `--remote-debugging-port=${PORT}`, `--user-data-dir=${profile}`,
  "--window-size=1400,900", "about:blank"], { stdio: "ignore" });

let target;
for (let i = 0; i < 40 && !target; i += 1) {
  try {
    const list = await (await fetch(`http://127.0.0.1:${PORT}/json/list`)).json();
    target = list.find((t) => t.type === "page");
  } catch { /* chrome is still coming up */ }
  if (!target) await sleep(500);
}
if (!target) { chrome.kill(); throw new Error("headless Chrome did not expose a CDP target"); }

const ws = new WebSocket(target.webSocketDebuggerUrl);
await new Promise((r) => ws.addEventListener("open", r, { once: true }));
let id = 1;
const pending = new Map();
ws.addEventListener("message", (event) => {
  const message = JSON.parse(event.data);
  if (message.id && pending.has(message.id)) { pending.get(message.id)(message); pending.delete(message.id); }
});
const send = (method, params = {}) =>
  new Promise((r) => { const i = id++; pending.set(i, r); ws.send(JSON.stringify({ id: i, method, params })); });
const evaluate = async (expression) =>
  (await send("Runtime.evaluate", { expression, returnByValue: true })).result?.result?.value;

await send("Page.enable");
await send("Runtime.enable");
await send("Page.navigate", { url: `file://${page}` });
let done = false;
for (let i = 0; i < 90 && !done; i += 1) { await sleep(1000); done = await evaluate("window.__done === true"); }

const failure = await evaluate("window.__err");
const encoded = failure ? null : await evaluate("window.__png");
ws.close(); chrome.kill(); await sleep(300);
rmSync(work, { recursive: true, force: true });

if (failure) { console.error(failure); process.exit(1); }
if (!encoded) { console.error("render timed out before the export finished"); process.exit(1); }
const png = Buffer.from(encoded, "base64");
writeFileSync(OUT, png);
console.log(`docs/THETASHIELD_FLOW.png — ${(png.length / 1024 / 1024).toFixed(2)} MB`);
